name: Test Under Load
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install lua
        uses: leafo/gh-actions-lua@v12

      - name: Run with 3 ints
        run: lua knockout.lua 1 2 3

      - name: Run with 4 ints
        run: lua knockout.lua 1 2 3 4

      - name: Run with 5 ints
        run: lua knockout.lua 1 2 3 4 5

      - name: Run with 6 ints
        run: lua knockout.lua 1 2 3 4 5 6

      - name: Run with 7 ints
        run: lua knockout.lua 1 2 3 4 5 6 7

      - name: Run absolutely crazy 10 ints
        run: lua knockout.lua 1 2 3 4 5 6 7 8 9 10
        continue-on-error: true
