name: Test Under Load

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  easy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install lua
        uses: leafo/gh-actions-lua@v12

      - name: Run 2
        run: lua knockout.lua 1 3 1 2
        timeout-minutes: 1

      - name: Run 3
        run: lua knockout.lua 1 9 1 2 3
        timeout-minutes: 1

      - name: Run 4
        run: lua knockout.lua 1 36 1 2 3 4
        timeout-minutes: 1

      - name: Run 5
        run: lua knockout.lua 1 64 1 2 3 4 5
        timeout-minutes: 1

  hard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install lua
        uses: leafo/gh-actions-lua@v12

      - name: Run 7
        run: lua knockout.lua 1 36 1 2 3 4 5 6 7
        timeout-minutes: 3
        continue-on-error: true

      - name: Run 5 6 11
        run: lua knockout.lua 1 36 5 6 11
        timeout-minutes: 2
        continue-on-error: true

      - name: Run with strange numbers
        run: lua knockout.lua -5 36 -5 0 .25
        timoute-minutes: 2
        continue-on-error: true
